### ISSUE TITLE
Cannot compile Vega-Lite with vega-lib

### ISSUE THREAD

**Issue by domoritz** [vega/vega-typings#13]
We currently cannot compile Vega-Lite with Vega-Lib because `vega-lib` does not declare typings for `vega`. This is related to https://github.com/vega/vega-typings/pull/8. 

I suggest that we either merge https://github.com/vega/vega-typings/pull/8 or add 

```
declare module 'vega' {
  export * from 'vega-typings';
}
```

to vega-lib. I'm not sure what is better.

**Comment by domoritz** [comment]
I had to add https://github.com/vega/vega-embed/blob/master/typings/vega.d.ts to Vega-Embed but I suspect that everyone depending on Vega-Embed has to do the same.

**Comment by pelotom** [comment]
> We currently cannot compile Vega-Lite with Vega-Lib because `vega-lib` does not declare typings for `vega`. This is related to https://github.com/vega/vega-typings/pull/8. 

`vega-lib` is reexporting `vega-typings`

https://github.com/vega/vega-lib/blob/804f650279d9a24ccef47e30ba07bf28d9e7b18c/index.d.ts#L1

but maybe it should be

```ts
declare module 'vega' {
  export * from 'vega-typings';
}
```

? Is `vega-lib` meant to be remapped to `vega`, or should people be using `import * as vega from 'vega-lib'`?

**Comment by domoritz** [comment]
If I delete https://github.com/vega/vega-embed/blob/master/typings/vega.d.ts from Vega-Embed, I get the following errors:

```
yarn build
yarn run v1.5.1
$ tsc -p .
node_modules/vega-lite/build/src/aggregate.d.ts(1,29): error TS2307: Cannot find module 'vega'.
node_modules/vega-lite/build/src/fielddef.d.ts(1,29): error TS2307: Cannot find module 'vega'.
node_modules/vega-lite/build/src/log.d.ts(4,29): error TS2307: Cannot find module 'vega'.
node_modules/vega-lite/build/src/sort.d.ts(1,29): error TS2307: Cannot find module 'vega'.
node_modules/vega-lite/build/src/transform.d.ts(1,29): error TS2307: Cannot find module 'vega'.
node_modules/vega-lite/build/src/vega.schema.d.ts(1,29): error TS2307: Cannot find module 'vega'.
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c tsc -p .
Directory: /Users/domoritz/Developer/UW/vega-embed
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/domoritz/Developer/UW/vega-embed/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The error is inside Vega-Lite. This would be fixed by setting

```
declare module 'vega' {
  export * from 'vega-typings';
}
``` 

I'm not sure what side effects that has, though. Would it make sense to set both like below?

```
declare module 'vega' {
  export * from 'vega-typings';
}

declare module 'vega-lib' {
  export * from 'vega-typings';
}
```

**Comment by pelotom** [comment]
> 
> I'm not sure what side effects that has, though. Would it make sense to set both like below?
> 
> ```ts
> declare module 'vega' {
>   export * from 'vega-typings';
> }
> 
> declare module 'vega-lib' {
>   export * from 'vega-typings';
> }
> ```

Hmm, I'm not sure... I wonder if people are using `vega-lib` by remapping it to `vega`, if that would cause weird conflicts? I really don't know.

**Comment by domoritz** [comment]
I don't know either but if we only define 

```
declare module 'vega' {
  export * from 'vega-typings';
}
```

then people who use vega-lib will not use typings, right (even if they map `vega-lib` to `vega`)?

**Comment by pelotom** [comment]
They would need to map `vega-lib` to `vega` in their `tsconfig.json`, but then it should work.

**Comment by domoritz** [comment]
> They would need to map vega-lib to vega in their tsconfig.json, but then it should work.

Ahh, I didn't know about this. Can you write this up in the vega-lib readme? I submitted a PR to change the type export in https://github.com/vega/vega-lib/pull/2.

**Comment by pelotom** [comment]
Hmm, actually it may not be so simple. This is what you can configure: https://www.typescriptlang.org/docs/handbook/module-resolution.html#virtual-directories-with-rootdirs

I think I was thinking of the `paths` option, but that's more useful for mapping relative modules to non-relative, whereas what we want here is just to treat `vega-lib` in all respects as `vega`.

In the end I think it actually may be simplest to just use

```ts
import * as vega from 'vega-lib';
```

everywhere in your code rather than somehow try to make `vega-lib` stand in for `vega`.

**Comment by domoritz** [comment]
Correct me if I'm wrong, but I think that won't work because we are using vega in vega-lite and vega-lib in vega-embed.

**Comment by pelotom** [comment]
I thought this was about trying to get `vega-lite` able to use `vega-lib` instead of `vega`?

**Comment by domoritz** [comment]
vega-lite cannot use vega-lib because we need canvas to build PNGs. Vega-embed depends on vega-lite and only uses vega-lib and thus doesn't compile. Sorry about the confusion. You can try to compile vega-embed but delete https://github.com/vega/vega-embed/blob/master/typings/vega.d.ts to see what I mean.

**Comment by domoritz** [comment]
Have you had a chance to look into this @pelotom?

**Comment by pelotom** [comment]
Sorry, I’ve been too busy lately with work to tend to open source endeavors. Hopefully will have some breathing room in a week or so.

**Comment by domoritz** [comment]
I'm having problems compiling vega-embed in jupyterlab unless I add 

```
declare module 'vega' {
  export * from 'vega-typings';
}

declare module 'vega-lib' {
  export * from 'vega-typings';
}
```

I sent a PR in https://github.com/vega/vega-lib/pull/3.
