### ISSUE TITLE
vega.Axis tickCount doesn't accept string values

### ISSUE THREAD

**Issue by jmattheis** [vega/vega-typings#19]
| Property | Type | Description
| -----------| ------------------ | ------ |
| tickCount | Number \| String \| Object | [...] For scales of type time or utc, the tick count can instead be a time interval specifier. Legal string values are "millisecond", "second", "minute", "hour", "day", "week", "month", and "year" [...] 

[Source (vega docs)](https://vega.github.io/vega/docs/axes/)

In [types/spec/axis.d.ts](https://github.com/vega/vega-typings/blob/master/types/spec/axis.d.ts) `tickCount` is `number | SignalRef` so string values are not valid.

Could you properly adjust the typings?

**Comment by pelotom** [comment]
PRs welcome 🙂
