### ISSUE TITLE
BC break typescript >=2.8

### ISSUE THREAD

**Issue by metanav** [vega/vega-typings#32]
After upgrading to vega@4.0.0:

`ERROR in node_modules/vega-typings/types/spec/util.d.ts(8,50): error TS2304: Cannot find name 'Exclude'.`

My app uses Angular 6 which is still at Typescript@2.7.2.
I guess **Exclude** was added in Typescript@2.8, so all apps below 2.8 will throw error.

**Comment by domoritz** [comment]
Thank you for the report. I'll look into it. For now, you can just pin the typings to an older version. Vega does not depend on a specific version.
