### ISSUE TITLE
Move this repo to the vega monorepo?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-typings#58]
Also, include some test that would force us to update this repo whenever Vega got new syntax?

**Comment by domoritz** [comment]
Yes, I agree. We already have some tests.

**Comment by RandomFractals** [comment]
+1 on both counts. 

This could def. use more work. Nice compilation in one place tho:

https://github.com/vega/vega-typings/blob/master/tests/spec/examples.ts

**Comment by jheer** [comment]
Use the lerna import command, relative to a local copy of the repo to import.

**Comment by domoritz** [comment]
And tests are being generated now: https://github.com/vega/vega/pull/1512
